import Test.Synthetic.ExpectFailureSelfTest
import Test.Synthetic.Edge
import Test.Synthetic.Universe
import Test.Synthetic.Witness
import Test.Synthetic.Refinement
import Test.Synthetic.Monotone
import Test.Synthetic.Report
import Test.Synthetic.ToyResearch
import Test.Synthetic.Replay
import Test.Synthetic.Split
import Test.Synthetic.Guarded
import Test.Synthetic.Escape
import Test.Synthetic.CandidateSeal
import Test.Synthetic.NegativeTests
import Test.Synthetic.Transition
import Test.Synthetic.Outcome
import Test.Synthetic.Stall
