import CRRGExamples.CruxFamily

/-! GENERATED by `families/gen_lean.py` from `families/demo.json`. Do not edit by hand.
`CRRGExamples/FamilyAgreement.lean` checks it against the Lean guard. The family is
synthetic. -/

namespace CRRGExamples.FamilyDemoJson

open CRRGExamples.CruxFamily

/-- The guard fields of `toy-edge` in JSON order: (id, kind). -/
def edgeFields : List (String × String) :=
  [("mode_1", "decidable"),
   ("m_odd", "decidable"),
   ("m_certified", "data"),
   ("k_divides", "decidable"),
   ("k_range", "decidable"),
   ("x_window", "decidable"),
   ("profile", "joint")]

/-- Every numeric constant in the JSON checks: (field, variable, op, value). -/
def edgeNumbers : List (String × String × String × Nat) :=
  [("mode_1", "mode", "==", 1),
   ("profile", "minDeg", ">=", 2),
   ("profile", "mass", "<=", 40)]

/-- Sample instances with the JSON checker's verdict. -/
def edgeSamples : List (String × Inst × Bool) :=
  [("aPass", ⟨1, 11, some true, 4, 20, 25, 30, some 2, 36⟩, true),
   ("bLow", ⟨1, 11, some true, 4, 20, 12, 30, none, 0⟩, false),
   ("cEven", ⟨2, 12, none, 2, 0, 0, 0, some 3, 50⟩, false),
   ("xAtLo", ⟨1, 11, some true, 4, 20, 20, 30, some 2, 36⟩, true),
   ("xAtHi", ⟨1, 11, some true, 4, 20, 30, 30, some 2, 36⟩, true),
   ("xAboveHi", ⟨1, 11, some true, 4, 20, 31, 30, some 2, 36⟩, false),
   ("massAtBudget", ⟨1, 11, some true, 4, 20, 25, 30, some 2, 40⟩, true),
   ("massOverBudget", ⟨1, 11, some true, 4, 20, 25, 30, some 2, 41⟩, false),
   ("degLow", ⟨1, 11, some true, 4, 20, 25, 30, some 1, 36⟩, false),
   ("noProfile", ⟨1, 11, some true, 4, 20, 25, 30, none, 36⟩, false),
   ("kZero", ⟨1, 11, some true, 0, 20, 25, 30, some 2, 36⟩, false),
   ("kNotDividing", ⟨1, 11, some true, 5, 20, 25, 30, some 2, 36⟩, false),
   ("kTooSmall", ⟨1, 11, some true, 2, 20, 25, 30, some 2, 36⟩, false),
   ("kTooLarge", ⟨1, 11, some true, 12, 20, 25, 30, some 2, 36⟩, false),
   ("mEven", ⟨1, 12, some true, 4, 20, 25, 30, some 2, 36⟩, false),
   ("noCertificate", ⟨1, 11, none, 4, 20, 25, 30, some 2, 36⟩, false),
   ("mode2", ⟨2, 11, some true, 4, 20, 25, 30, some 2, 36⟩, false)]

end CRRGExamples.FamilyDemoJson
