#!/usr/bin/env python3
"""Generate CRRGExamples/FamilyDemoJson.lean from families/demo.json (a synthetic crux family).

The generated file carries, as Lean data:
  * the shared edge's guard field ids and kinds, in JSON order;
  * every numeric constant in the JSON checks, as (field, variable, op, value);
  * the JSON checker's verdicts (runner/guard_fields.evaluate) on a fixed set of sample instances.
`CRRGExamples/FamilyAgreement.lean` then checks by `decide` that the Lean guard has the same fields,
kinds and numbers, and gives the same verdict on every sample.

build.sh runs this with --check and fails if the committed copy differs, so the JSON and the Lean
model cannot drift apart silently.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(PKG, "runner"))
from guard_fields import evaluate  # noqa: E402

FAMILY = "demo.json"
EDGE = "toy-edge"
OUT = os.path.join(PKG, "CRRGExamples", "FamilyDemoJson.lean")

# Samples (synthetic): the members of CruxFamily plus edge cases, one field varied at a time.
# Fields, in the order of CruxFamily.Inst: mode, m, mCertified, k, lo, x, hi, minDeg, mass.
KEYS = ["mode", "m", "mCertified", "k", "lo", "x", "hi", "minDeg", "mass"]
DATA_FIELD_VAR = {"m_certified": "mCertified"}
OK = (1, 11, True, 4, 20, 25, 30, 2, 36)


def vary(**changes):
    inst = dict(zip(KEYS, OK))
    inst.update(changes)
    return tuple(inst[k] for k in KEYS)


SAMPLES = [
    ("aPass", OK),
    ("bLow", vary(x=12, minDeg=None, mass=0)),
    ("cEven", (2, 12, None, 2, 0, 0, 0, 3, 50)),
    ("xAtLo", vary(x=20)),
    ("xAtHi", vary(x=30)),
    ("xAboveHi", vary(x=31)),
    ("massAtBudget", vary(mass=40)),
    ("massOverBudget", vary(mass=41)),
    ("degLow", vary(minDeg=1)),
    ("noProfile", vary(minDeg=None)),
    ("kZero", vary(k=0)),
    ("kNotDividing", vary(k=5)),
    ("kTooSmall", vary(k=2)),
    ("kTooLarge", vary(k=12)),
    ("mEven", vary(m=12)),
    ("noCertificate", vary(mCertified=None)),
    ("mode2", vary(mode=2)),
]


def verdict(guard, inst):
    env = {k: v for k, v in zip(KEYS, inst) if v is not None}
    for g in guard:
        if g["kind"] == "data":
            if env.get(DATA_FIELD_VAR[g["id"]]) is not True:
                return False
        elif not evaluate(g["check"], env):
            return False
    return True


def numbers(guard):
    out = []

    def walk(fid, chk):
        if "all" in chk:
            for c in chk["all"]:
                walk(fid, c)
        elif isinstance(chk.get("value"), int):
            out.append((fid, chk["var"], chk["op"], chk["value"]))

    for g in guard:
        if "check" in g:
            walk(g["id"], g["check"])
    return out


def lean_opt(v):
    if v is None:
        return "none"
    if isinstance(v, bool):
        return f"some {str(v).lower()}"
    return f"some {v}"


def main():
    fam = json.load(open(os.path.join(HERE, FAMILY), encoding="utf-8"))
    guard = fam["shared_edges"][EDGE]["guard"]
    lines = [
        "import CRRGExamples.CruxFamily",
        "",
        f"/-! GENERATED by `families/gen_lean.py` from `families/{FAMILY}`. Do not edit by hand.",
        "`CRRGExamples/FamilyAgreement.lean` checks it against the Lean guard. The family is",
        "synthetic. -/",
        "",
        "namespace CRRGExamples.FamilyDemoJson",
        "",
        "open CRRGExamples.CruxFamily",
        "",
        f"/-- The guard fields of `{EDGE}` in JSON order: (id, kind). -/",
        "def edgeFields : List (String × String) :=",
        "  [" + ",\n   ".join(f'("{g["id"]}", "{g["kind"]}")' for g in guard) + "]",
        "",
        "/-- Every numeric constant in the JSON checks: (field, variable, op, value). -/",
        "def edgeNumbers : List (String × String × String × Nat) :=",
        "  [" + ",\n   ".join(f'("{a}", "{b}", "{c}", {d})' for a, b, c, d in numbers(guard)) + "]",
        "",
        "/-- Sample instances with the JSON checker's verdict. -/",
        "def edgeSamples : List (String × Inst × Bool) :=",
    ]
    rows = []
    for name, inst in SAMPLES:
        (mode, m, mc, k, lo, x, hi, deg, mass) = inst
        lean_inst = (f"⟨{mode}, {m}, {lean_opt(mc)}, {k}, {lo}, {x}, {hi}, {lean_opt(deg)}, "
                     f"{mass}⟩")
        rows.append(f'("{name}", {lean_inst}, {str(verdict(guard, inst)).lower()})')
    lines.append("  [" + ",\n   ".join(rows) + "]")
    lines += ["", "end CRRGExamples.FamilyDemoJson", ""]
    text = "\n".join(lines)
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("FamilyDemoJson.lean is stale: run python3 families/gen_lean.py")
            return 1
        print(f"FamilyDemoJson.lean is up to date with families/{FAMILY}")
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
